// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace protabula.Migrations
{
    [DbContext(typeof(ScrapperDbContext))]
    partial class ScrapperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PrimaryRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("RatingRange")
                        .HasColumnType("REAL");

                    b.Property<float>("RatingValue")
                        .HasColumnType("REAL");

                    b.Property<string>("ReviewId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId")
                        .IsUnique();

                    b.ToTable("PrimaryRatings");
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentLocale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsForeign")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerifiedBuyer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LatestModificationOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("NegativeFeedbacksCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositiveFeedbacksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceCountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmissionOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SecondaryRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("RatingRange")
                        .HasColumnType("REAL");

                    b.Property<float>("RatingValue")
                        .HasColumnType("REAL");

                    b.Property<string>("ReviewId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("SecondaryRatings");
                });

            modelBuilder.Entity("PrimaryRating", b =>
                {
                    b.HasOne("Review", null)
                        .WithOne("PrimaryRating")
                        .HasForeignKey("PrimaryRating", "ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SecondaryRating", b =>
                {
                    b.HasOne("Review", null)
                        .WithMany("SecondaryRatings")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.Navigation("PrimaryRating")
                        .IsRequired();

                    b.Navigation("SecondaryRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
